/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vnd_blueararat_Effoto_MTRNGJNILib */

#ifndef _Included_vnd_blueararat_Effoto_MTRNGJNILib
#define _Included_vnd_blueararat_Effoto_MTRNGJNILib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vnd_blueararat_Effoto_MTRNGJNILib
 * Method:    randomize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_vnd_blueararat_Effoto_MTRNGJNILib_randomize
  (JNIEnv *, jclass);

/*
 * Class:     vnd_blueararat_Effoto_MTRNGJNILib
 * Method:    rand
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_vnd_blueararat_Effoto_MTRNGJNILib_rand__
  (JNIEnv *, jclass);

/*
 * Class:     vnd_blueararat_Effoto_MTRNGJNILib
 * Method:    rand
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_vnd_blueararat_Effoto_MTRNGJNILib_rand__F
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     vnd_blueararat_Effoto_MTRNGJNILib
 * Method:    randExc
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_vnd_blueararat_Effoto_MTRNGJNILib_randExc__
  (JNIEnv *, jclass);

/*
 * Class:     vnd_blueararat_Effoto_MTRNGJNILib
 * Method:    randExc
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_vnd_blueararat_Effoto_MTRNGJNILib_randExc__F
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     vnd_blueararat_Effoto_MTRNGJNILib
 * Method:    randDblExc
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_vnd_blueararat_Effoto_MTRNGJNILib_randDblExc__
  (JNIEnv *, jclass);

/*
 * Class:     vnd_blueararat_Effoto_MTRNGJNILib
 * Method:    randDblExc
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_vnd_blueararat_Effoto_MTRNGJNILib_randDblExc__F
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     vnd_blueararat_Effoto_MTRNGJNILib
 * Method:    randNorm
 * Signature: (FF)F
 */
JNIEXPORT jfloat JNICALL Java_vnd_blueararat_Effoto_MTRNGJNILib_randNorm
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     vnd_blueararat_Effoto_MTRNGJNILib
 * Method:    randInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_vnd_blueararat_Effoto_MTRNGJNILib_randInt__
  (JNIEnv *, jclass);

/*
 * Class:     vnd_blueararat_Effoto_MTRNGJNILib
 * Method:    randInt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_vnd_blueararat_Effoto_MTRNGJNILib_randInt__I
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
